version: "3.9" 

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - consul

  consul-server:
    image: hashicorp/consul:1.11.2
    container_name: consul-server
    restart: always
    volumes:
      - ./server.json:/consul/config/server.json:ro
      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    # command: "agent -bootstrap-expect=3"

networks:
  consul:
    driver: bridge